#pragma once

#include <cppy3/cppy3_export.h>

#if (defined(_WIN32) || defined(__CYGWIN__))
    #pragma warning(disable : 4996 4244 4180 4800 4661)
#endif

// Real dllexport/dllimport (Windows) and visibility (POSIX) annotations,
// generated by CMake's GenerateExportHeader from the cppy3 target's actual
// build type (shared vs static). LIB_API is kept as an alias so existing
// declarations do not need to change.
#define LIB_API CPPY3_API
